
SELECT
	S.ID_SECTOR,
	S.DESCRIPCION,
	SUM(CASE WHEN C.ESTADO = 'LIBRE' THEN 1 ELSE 0 END) AS CANT_CAMAS_LIBRES
FROM CAMA c 
INNER JOIN HABITACION h
	ON C.NRO_HABITACION = H.NRO_HABITACION 
INNER JOIN SECTOR s 
	ON H.ID_SECTOR = S.ID_SECTOR 
GROUP BY S.ID_SECTOR, S.DESCRIPCION 
ORDER BY 1,2;

SELECT
	S.ID_SECTOR,
	S.DESCRIPCION,
	C.NRO_HABITACION,
	C.NRO_CAMA
FROM CAMA c 
INNER JOIN HABITACION h
	ON C.NRO_HABITACION = H.NRO_HABITACION 
INNER JOIN SECTOR s 
	ON H.ID_SECTOR = S.ID_SECTOR 
WHERE C.ESTADO = 'LIBRE'
ORDER BY 1,2,3,4;