/* Scripts para la eliminacion de las tablas del modelo relacional en Oracle */

ALTER SESSION SET CONTAINER = FREEPDB1;
-- Set the current schema to the hospital schema
ALTER SESSION SET CURRENT_SCHEMA = hospital;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PERSONA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PACIENTE CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE MEDICO CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE SECTOR CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE HABITACION CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE CAMA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ESPECIALIDAD CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE SE_ESPECIALIZA_EN CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TURNO CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE RONDA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE VISITA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE INTERNACION CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE SE_UBICA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE RECORRIDO CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE COMENTA_SOBRE CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE GUARDIA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ATIENDE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN -- -942: table or view does not exist
            RAISE;
        END IF;
END;
/
