/* Scripts para la creacion de las tablas (definicion de PKs) del modelo relacional en Oracle */

ALTER SESSION SET CONTAINER = FREEPDB1;
-- Set the current schema to the hospital schema
ALTER SESSION SET CURRENT_SCHEMA = hospital;

-- Persona(tipo_documento, nro_documento, nombre, apellido, tipo)
CREATE TABLE PERSONA (
    tipo_documento VARCHAR2(10)  NOT NULL,
    nro_documento  VARCHAR2(20)  NOT NULL,
    nombre         VARCHAR2(100) NOT NULL,
    apellido       VARCHAR2(100) NOT NULL,
    tipo           VARCHAR2(50)  NOT NULL,
    CONSTRAINT pk_persona PRIMARY KEY (tipo_documento, nro_documento)
);

-- Paciente(*tipo_documento*, *nro_documento*, fecha_nacimiento, sexo)
CREATE TABLE PACIENTE (
    tipo_documento   VARCHAR2(10) NOT NULL,
    nro_documento    VARCHAR2(20) NOT NULL,
    fecha_nacimiento DATE    NOT NULL,
    sexo             CHAR(1) NOT NULL,
    CONSTRAINT pk_paciente PRIMARY KEY (tipo_documento, nro_documento)
);

-- Medico(matricula, cuilcuit, fecha_ingreso, foto, max_cant_guardia, periodo_vacaciones, *tipo_documento, nro_documento*)
CREATE TABLE MEDICO (
    matricula          NUMBER(10)   PRIMARY KEY,
    cuil_cuit          VARCHAR2(20) NOT NULL UNIQUE,
    fecha_ingreso      DATE NOT NULL,
    foto               BLOB,
    max_cant_guardia   NUMBER(5)    DEFAULT 0 NOT NULL,
    periodo_vacaciones VARCHAR2(50) NOT NULL,
    tipo_documento     VARCHAR2(10) NOT NULL,
    nro_documento      VARCHAR2(20) NOT NULL
);

-- Sector(id_sector, descripcion)
CREATE TABLE SECTOR (
    id_sector   NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 1) PRIMARY KEY,
    descripcion VARCHAR2(100) NOT NULL
);

-- Habitacion(nro_habitacion, piso, orientacion, *id_sector*)
CREATE TABLE HABITACION (
    nro_habitacion NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) PRIMARY KEY,
    piso           NUMBER(5)    NOT NULL,
    orientacion    VARCHAR2(20) NOT NULL,
    id_sector      NUMBER(10)   NOT NULL
);

-- Cama(nro_cama, *nro_habitacion*, estado)
CREATE TABLE CAMA (
    nro_habitacion NUMBER(10)   NOT NULL,
    nro_cama       NUMBER(10)   NOT NULL,
    estado         VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_cama PRIMARY KEY (nro_cama, nro_habitacion)
);

-- Especialidad(cod_especialidad, descripcion, *id_sector*)
CREATE TABLE ESPECIALIDAD (
    cod_especialidad NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 100) PRIMARY KEY,
    descripcion      VARCHAR2(100) NOT NULL,
    id_sector        NUMBER(10)    NOT NULL
);

-- Se_Especializa_En(*matricula*, *cod_especialidad*, hace_guardia)
CREATE TABLE SE_ESPECIALIZA_EN (
    matricula        NUMBER(10) NOT NULL,
    cod_especialidad NUMBER(10) NOT NULL,
    hace_guardia     NUMBER(1)  DEFAULT 0 NOT NULL,
    CONSTRAINT pk_se_especializa_en PRIMARY KEY (matricula, cod_especialidad)
);

-- Turno(id_turno, horario)
CREATE TABLE TURNO (
    id_turno NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 1) PRIMARY KEY,
    horario  VARCHAR2(50) NOT NULL
);

-- Ronda(id_ronda, dia_semana, turno)
CREATE TABLE RONDA (
    id_ronda    NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_semana  VARCHAR2(15) NOT NULL,
    turno       VARCHAR2(20) NOT NULL
);

-- Visita(*id_ronda*, *nro_habitacion*)
CREATE TABLE VISITA (
    id_ronda       NUMBER(10) NOT NULL,
    nro_habitacion NUMBER(10) NOT NULL,
    CONSTRAINT pk_visita PRIMARY KEY (id_ronda, nro_habitacion)
);

-- Internacion(nro_internacion, fecha_inicio, fecha_fin, *tipo_documento, nro_documento, matricula*)
CREATE TABLE INTERNACION (
    nro_internacion NUMBER(10)  GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) PRIMARY KEY, -- Comienza en 11 para evitar conflicto con datos de prueba!!!
    fecha_inicio    DATE NOT NULL,
    fecha_fin       DATE,
    tipo_documento  VARCHAR2(10) NOT NULL,
    nro_documento   VARCHAR2(20) NOT NULL,
    matricula       NUMBER(10)   NOT NULL
);

-- Se_Ubica(*nro_internacion*, *nro_cama*, *nro_habitacion*, fecha_hora_ingreso)
CREATE TABLE SE_UBICA (
    nro_internacion    NUMBER(10) NOT NULL,
    fecha_hora_ingreso TIMESTAMP  NOT NULL,
    nro_cama           NUMBER(10) NOT NULL,
    nro_habitacion     NUMBER(10) NOT NULL,
    CONSTRAINT pk_se_ubica PRIMARY KEY (nro_internacion, fecha_hora_ingreso)
);

-- Recorrido(id_recorrido, fecha_recorrido, hora_inicio, hora_fin, *id_ronda, matricula*)
CREATE TABLE RECORRIDO (
    id_recorrido    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) PRIMARY KEY,
    fecha_recorrido DATE NOT NULL,
    hora_inicio     TIMESTAMP  NOT NULL,
    hora_fin        TIMESTAMP  NOT NULL,
    id_ronda        NUMBER(10) NOT NULL,
    matricula       NUMBER(10) NOT NULL
);

-- Comenta_Sobre(*id_recorrido*, *nro_internacion*, comentario)
CREATE TABLE COMENTA_SOBRE (
    id_recorrido    NUMBER(10) NOT NULL,
    nro_internacion NUMBER(10) NOT NULL,
    comentario      CLOB NOT NULL,
    CONSTRAINT pk_comenta_sobre PRIMARY KEY (id_recorrido, nro_internacion)
);

-- Guardia(nro_guardia, fecha_hora, *matricula, cod_especialidad, id_turno*)
CREATE TABLE GUARDIA (
    nro_guardia      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) PRIMARY KEY,
    fecha_hora       TIMESTAMP  NOT NULL,
    matricula        NUMBER(10) NOT NULL,
    cod_especialidad NUMBER(10) NOT NULL,
    id_turno         NUMBER(10) NOT NULL
);

-- Atiende(cod_especialidad, id_turno)
CREATE TABLE ATIENDE (
    cod_especialidad NUMBER(10) NOT NULL,
    id_turno         NUMBER(10) NOT NULL,
    CONSTRAINT pk_atiende PRIMARY KEY (cod_especialidad, id_turno)
);

-- Necesitamos una tabla de auditoria para las modificaciones en las guardias
CREATE TABLE AUDITORIA_GUARDIA (
    id_auditoria      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora_reg    TIMESTAMP      NOT NULL,   -- cuándo se hizo el cambio
    usuario_bd        VARCHAR2(50)   NOT NULL,   -- USER que ejecutó el cambio
    operacion         VARCHAR2(10)   NOT NULL,   -- 'INSERT', 'UPDATE', 'DELETE'
    nro_guardia       NUMBER(10),                -- guardia afectada
    fecha_hora_guard  TIMESTAMP,                 
    matricula         NUMBER(10),
    cod_especialidad  NUMBER(10),
    id_turno          NUMBER(10),
    detalle_old       VARCHAR2(4000),
    detalle_new       VARCHAR2(4000)
);
